### ISSUE TITLE
Customize paths to CSS and JS files?

### ISSUE THREAD

**Issue by clintlalonde** [BCIT-LTC/dewordify#4]
Nice work! I noticed that the path to the CSS and JS files in the generated HTML code point back to files at BCIT. Are there ways to customize the CSS or JS file references?
![dewordify](https://user-images.githubusercontent.com/679506/26942335-83e7c6e4-4c36-11e7-87db-2a3b8c5037a4.PNG)

**Comment by MCTaylor17** [comment]
I would suggest using a custom template.

Place a file named `template.html` into the same folder as your word document before running dewordify and it will use that one instead of our default.

It will unfortunately need a tag with class="container" on it so that Dewordify knows where to place the content, but that also allows you to include custom headers and footers in your template file :wink:

You can also place the template up to 3 folders above your word document which allows for course, program, and school level templating.

Documentation on the use of templates will need to be generated.  I'll leave this open as a reminder.

**Comment by MCTaylor17** [comment]
I've added a 'Customization' section to the README file outlining some of the various methods for getting more out of Dewordify.  

It's a first draft, but we work in the open.   Please post a new issue if you find the documentation unclear.
