### ISSUE TITLE
renaming and re-locating template.html

### ISSUE THREAD

**Issue by kphunter** [BCIT-LTC/dewordify#40]
We received feedback that the template.html file is difficult to find when it is listed in a directory with lots of other files.

How can we ensure the filename `template.html` file is easy to find when it is located in a folder populated with hundreds of other files?

Also, the feedback suggested it was difficult to find the `template.html` file when it was buried within the `modules` folder of the [course skeleton](https://github.com/BCIT-LTC/course-skeleton).

How can we make it easier to locate the `template.html` file?

**Comment by kphunter** [comment]
One solution that was proposed was to rename the `template.html` file to `_template.html`.

And in order to make it easier to locate the `template.html` file, it was also proposed that it be moved out of the `modules` folder into the root of the [course skeleton](https://github.com/BCIT-LTC/course-skeleton).

**Comment by MCTaylor17** [comment]
@kphunter I thought we were going to document this in Importerer?

I don't think this needs to impact either Dewordify or the course skeleton.  Importerer could simply place a copy of `template.html` wherever we want with whatever name we want.

**Comment by kphunter** [comment]
But if we rename `template.html` to `_template.html` in the skeleton, Dewordify will need to understand that change.

As I understand it, it shouldn't matter if we relocate the file up a directory.

**Comment by MCTaylor17** [comment]
@kphunter 

The change you're proposing will be disruptive to on-going builds.  Contrast that with changing it in Importerer where everything can remain as it is.

**Comment by kphunter** [comment]
We can avoid disruption if we simply add `OR` logic... And by moving the `_template.html` file out of the modules folder into the root, it also makes it easier for the [course support folks](https://www.bcit.ca/ltc/services/edtechsupport.shtml).

**Comment by MCTaylor17** [comment]
It's not as simple as adding an if-else branch to the code.  Dewordify finds the template file using using a `fileFinder` function which searches a given number of parent folders.  If the file can't be found, it returns a relative path to the "default-files" contained in Dewordify.  The problem is, the template file isn't the only file Dewordify looks for with this function.

Here's roughly what a "simple" if statement would look like:

```js
var styleMapPath = fileFinder("styleMap.txt");
var markoutMapPath = fileFinder("markoutMap.json");

// Look for the new template file
var templatePath = fileFinder("_template.html"); 

// If the newer template file was not found
if(templatePath === "../../default-files/_template.html") {
  
  // Look for the legacy file
  var legacyTemplatePath = fileFinder("template.html");

  // If the legacy file was found
  if(legacyTemplatePath !== "../../default-files/template.html") {

    // Use it instead of the new default template path
    templatePath = oldTemplatePath;
  }
}
```

I don't know about you, but I really dislike this approach because it adds a bunch of convoluted logic to the entry point of the application.

Alternatively, the fileFinder module could be changed, but that would mean creating some kind of iterator so that we could say:

```js
var styleMapPath = fileFinder("styleMap.txt");
var markoutMapPath = fileFinder("markoutMap.json");
var templatePath = fileFinder(["_template.html","template.html"]); 
```

But now the fileFinder module is going to need a bunch of additional logic to type check the first parameter.  It's an ugly mess no matter how we cut it.

**Comment by MCTaylor17** [comment]
Further to the reservations mentioned above, we can't avoid making changes to Importerer.  It's rather selective of which files are zipped, so if we move the template to the root, we'll have to specifically include that file in the zip.

That means we can either just change importerer, or we can change importerer, dewordify, and the course skeleton.

**Comment by kphunter** [comment]
abandoning this issue
