### ISSUE TITLE
YouTube embed code needs updating

### ISSUE THREAD

**Issue by kphunter** [BCIT-LTC/dewordify#65]
More often than not, YouTube source video URL's are copied directly from the browser URL field, rather than from the **"share" -> "embed"** area. This means we always have to adjust the iframe source from `https://.../watch?...` to `https://.../embed/...`.

IMO this should be automated...

Also, be wary of more complicated URL's like those that specify *playlists*.

**Comment by kphunter** [comment]
Apparently the regex needs tweaking... this doesn't render correctly:

![youtube-link](https://user-images.githubusercontent.com/5122386/42003627-4a64cd4e-7a21-11e8-92ba-746974da599c.PNG)

**Comment by MCTaylor17** [comment]
NPM or even vanilla JavaScript probably have simple tools for working with query parameters.  I know there's `location.hash` to get the anchor.  I never liked query strings myself.  I think it's a horrible user experience, but in this case it would all be automated.

You remember me telling you how cool YouTube's API was.  There's a lot of fun things that can be done, like skinning, time start/end times (SUPER useful!!), turning on closed captioning by default, and so much more.

It was always low priority though because of...  Well... Priorities...

**Comment by MCTaylor17** [comment]
In fact, give me a day or two to try and dig something out of my H-Drive.

Hope you enjoyed the LTC barbeque.  I completely forgot that was today.

**Comment by MCTaylor17** [comment]
I'm really liking the problem definition of this issue BTW ;)

**Comment by MCTaylor17** [comment]
I suggested in a comment somewhere on a commit that you could populate sliders full of playlist videos...

https://stackoverflow.com/questions/18804904/retrieve-all-videos-from-youtube-playlist-using-youtube-v3-api
