### ISSUE TITLE
`self-check` terminology updated to `knowledge-check`

### ISSUE THREAD

**Issue by kphunter** [BCIT-LTC/dewordify#74]
The `markout-map.json` file needs to reflect the change that has been made to the `self-check` terminology...

**Comment by MCTaylor17** [comment]
May I suggest a less disruptive change?  Keep `"self-test": "<div class='self-test'>"` and add `"knowledge-check": "<div class='self-test'>"`.

**Comment by kphunter** [comment]
That would be more of a temporary fix and it would eventually need to be changed... why not rip off the band-aid?

**Comment by MCTaylor17** [comment]
Because you'll still have old static HTML course content in the LMS with `class="self-test"`.

Getting the name right the first time is the ideal solution.  I wasn't privy to the conversation that necessitated this change, but I know we performed due diligence to come up with the original name.  We did that for exactly this reason, to avoid "crufting" the codebase due to a rename.

The second best alternative to getting the name right in the first place is to map new jargon to the existing interface.  That's ideal when it's one team of course-developers objecting to established naming standards.

In the event of a wholesale rejection of the established name, requiring even the HTML to reflect revised name, first I'd be curious "why" followed by 4 more "whys".  Second, I would be very careful to do so in a way that doesn't break old-content.  That would mean ensuring both the old name and new name perform identically.  The only way I can think to do that is by adding cruft to the CSS/JS due to the difficulties updating HTML in the LMS.

Keep in mind, major version bumps are designed for "breaking changes" like making changes to the HTML-interface.  What I'm proposing is simply to delay deep changes until you're ready for the next major release of Sugar Suite.

I'm pretty sure I've made this exact argument in the past.  It optimizes for stability in the codebase where things are most likely to go wrong.

**Comment by MCTaylor17** [comment]
I just had an example come to mind that will help illustrate the value of maintaining stability in the HTML API: Retrofitting.

As you may know, one of the primary difficulties of using Makeoverer is not in the tool itself, but rather the complexity of the HTML input.  The lack of stable naming conventions and agreed upon semantics led to a massive proliferation of HTML classes.  When I scraped the course development folder, there were something like 150 CSS classes that appeared to use instructional language.  Part of that was syntax deviations like abbreviations, hyphens, underscores, casing, etc.  

Controlling for those factors only reduced it to about 50.  The challenge then was that some names had both obvious and not so obvious synonyms.  That's what necessitated all of the card sorting activities and the affinity analysis to try and produce a single instructional language CSS/JS framework.

So, if we started the endeavor to try and curb the ever shifting proliferation of names and bring a semblance of sanity into online courses, how far have we come if we continue to shift the HTML API on a term-by term basis.

Let me being this back full-circle.  Wouldn't it be nice if Makeoverer was a push-button tool that'll could easily update a course from Sugar Suite v1 to Whatever Framework v42 because every page of HTML ever produced on in that version had 100% consistent HTML classes, despite the shifting tides of instructional nomenclature.

As it stands, updating from Sugar Suite v1 to vX is going to be an annoyance because there really isn't a v1.  There's just a patchwork of HTML files created over time.  I purposely built the markoutMap to allow for even document level deviations in naming so that #exercise #task #challenge #skill-check or even #fail-fast can all be mapped appropriately to class="activity".  That would mean that at some unknown point in the future, when all of the IDCs and SMEs have long since moved on with their lives, the maintenance of that content will no more difficult to deal with than anything else produced at the time.

Even in shorter time scales, if a new LTS was hired on tomorrow, they will one day happen upon `self-test` and have a "what the..." moment.

I know that treating the HTML as some kind of living standard has a semblance of desirability, but code isn't smart.  If you have any intentions of using code to transform the HTML produced today into other formats in the future, you're going to want a stationary target for as long as possible.

**Comment by MCTaylor17** [comment]
I hope it's clear these comments are not specific to the renaming of this one feature. 
I think they should inform a much higher level philosophy of course production.  The cost of failing to get the name right from the beginning (or failing to defend decisions made in the past) is one of two things:
1. Consistency of the HTML API
2. Consistency of the HTML API with the language du-jour.

As a programmer, I would much prefer dealing with normalized HTML.  I'm not sure what good "ripping off the bandaid" does if it's simply going to cause more pain in the future...

**Comment by kphunter** [comment]
I agree that getting the name right at the beginning is very important, which is why terminology changes are avoided at _almost_ all costs. The `#self-test` marker was causing a significant amount of confusion both within our team and our department, as well as external subject experts who were crafting the build files.

The Sugar Suite v1 js source referenced `#self-test` in 6 places and a find+replace was pretty straightforward to make the requested change to `#knowledge-check`. We also added a `.knowledge-check` class to the sass files to accommodate the change, but more importantly it demonstrated our agility, willingness, and ability to respond to the requested change.

**Comment by MCTaylor17** [comment]
> The Sugar Suite v1 js source referenced #self-test in 6 places and a find+replace was pretty straightforward

How many self-tests needed to be updated in D2L?
